DROP TABLE QuiSeConnecte;
CREATE TABLE QuiSeConnecte (
    USERNAME VARCHAR2(100),
    IP_ADDRESS VARCHAR2(100),
    CONNECT_TIME TIMESTAMP
);

-- GRANT ADMINISTER DATABASE TRIGGER TO e20190002767;

CREATE OR REPLACE TRIGGER ConnexionTrigger
AFTER LOGON ON DATABASE
BEGIN
    INSERT INTO QuiSeConnecte (USERNAME, IP_ADDRESS, CONNECT_TIME)
    VALUES (SYS_CONTEXT('USERENV', 'SESSION_USER'), SYS_CONTEXT('USERENV', 'IP_ADDRESS'), SYSTIMESTAMP);
END;
/